export const CATEGORIES = [
  {
    name: "VN30",
    displayName: "VN30",
    stocks: [
      "ACB",
      "BCM",
      "BID",
      "BVH",
      "CTG",
      "FPT",
      "GAS",
      "GVR",
      "HDB",
      "HPG",
      "MBB",
      "MSN",
      "MWG",
      "PLX",
      "POW",
      "SAB",
      "SHB",
      "SSB",
      "SSI",
      "STB",
      "TCB",
      "TPB",
      "VCB",
      "VHM",
      "VIB",
      "VIC",
      "VJC",
      "VNM",
      "VPB",
      "VRE",
    ],
  },
  {
    name: "NGAN_HANG",
    displayName: "NGÂN HÀNG",
    stocks: [
      "ABB",
      "ACB",
      "BAB",
      "BID",
      "BVB",
      "CTG",
      "EIB",
      "HDB",
      "KLB",
      "LPB",
      "MBB",
      "MSB",
      "NAB",
      "NVB",
      "OCB",
      "PGB",
      "SGB",
      "SHB",
      "STB",
      "TCB",
      "TPB",
      "VBB",
      "VCB",
      "VIB",
      "VPB",
      "SSB",
      "VAB",
    ],
  },
  {
    name: "BDS",
    displayName: "BĐS",
    stocks: [
      "HDC",
      "TCH",
      "DXG",
      "DIG",
      "CEO",
      "NTL",
      "DPG",
      "ITC",
      "KDH",
      "L14",
      "NDN",
      "NLG",
      "NVL",
      "PDR",
      "SJS",
      "VIC",
      "DIH",
      "SAM",
      "VHM",
      "NHA",
      "PTB",
      "TDC",
      "CSC",
      "HHS",
      "SCI",
      "CRE",
      "HLD",
      "AGG",
      "NRC",
      "LDG",
      "SCR",
      "HDG",
      "S99",
      "DXS",
      "KHG",
      "HQC",
    ],
  },
  {
    name: "CHUNG_KHOAN",
    displayName: "CHỨNG KHOÁN",
    stocks: [
      "SSI",
      "HCM",
      "VND",
      "VCI",
      "SHS",
      "VIX",
      "MBS",
      "AGR",
      "ORS",
      "FTS",
      "BSI",
      "CTS",
      "VDS",
      "BVS",
      "APG",
      "APS",
      "EVS",
      "HBS",
      "IVS",
      "PSI",
      "TVB",
      "TVS",
      "VFS",
      "VIG",
      "WSS",
      "TCI",
    ],
  },
  {
    name: "THEP",
    displayName: "THÉP - SẢN PHẨM TỪ THÉP",
    stocks: [
      "NSH",
      "VGS",
      "HPG",
      "SHA",
      "TVN",
      "NKG",
      "HSG",
      "POM",
      "TLH",
      "SHI",
      "SMC",
    ],
  },
  {
    name: "DAU_KHI",
    displayName: "DẦU KHÍ",
    stocks: ["PVS", "PVD", "PVC", "PVB", "GAS", "PVT", "OIL", "BSR", "PSH"],
  },
  {
    name: "BAO_HIEM",
    displayName: "BẢO HIỂM",
    stocks: ["BMI", "BVH", "BIC", "MIG", "PVI", "PGI", "PRE", "PTI", "VNR"],
  },
  {
    name: "BDS_KCN",
    displayName: "BĐS-KCN",
    stocks: [
      "D2D",
      "GVR",
      "IDC",
      "ITA",
      "KBC",
      "LDG",
      "LHG",
      "NLG",
      "NTC",
      "PHR",
      "QCG",
      "SIP",
      "SZC",
      "SZL",
      "BCM",
      "TDC",
      "TIG",
      "TIP",
      "VGC",
    ],
  },
  {
    name: "DAU_TU_CONG",
    displayName: "ĐẦU TƯ CÔNG",
    stocks: [
      "BCC",
      "BTS",
      "C32",
      "C47",
      "C4G",
      "CII",
      "CTI",
      "DHA",
      "FCN",
      "G36",
      "HOM",
      "HT1",
      "KSB",
      "LCG",
      "SD5",
      "SD6",
      "SD9",
      "TCD",
      "THG",
      "TV2",
    ],
  },
  {
    name: "XD_VLXD",
    displayName: "XD-VLXD",
    stocks: [
      "VCG",
      "VC7",
      "HU4",
      "MST",
      "VC3",
      "ACC",
      "QNC",
      "SCL",
      "VGC",
      "BCE",
      "CSC",
      "HTI",
      "TTB",
      "APC",
      "C69",
      "CDO",
      "CRC",
      "HID",
      "HVH",
      "LIG",
      "PAS",
      "S99",
      "SCG",
      "SCI",
      "TLD",
      "UDJ",
      "EVG",
      "CTD",
      "PHC",
      "CKG",
    ],
  },
  {
    name: "THAN_KHOANGSAN",
    displayName: "THAN - KHOÁNG SẢN",
    stocks: [
      "CLX",
      "KSB",
      "MDC",
      "NBC",
      "NNC",
      "TDN",
      "THT",
      "TVD",
      "VEF",
      "CST",
      "BMC",
      "DHM",
      "KHB",
      "KSQ",
      "MSR",
      "TC6",
      "TNT",
    ],
  },
  {
    name: "DET_MAY",
    displayName: "DỆT MAY",
    stocks: [
      "ADS",
      "EVE",
      "FTM",
      "GIL",
      "KMR",
      "MSH",
      "STK",
      "TCM",
      "TNG",
      "VGT",
    ],
  },
  {
    name: "VANTAI_CANG",
    displayName: "VẬN TẢI - CẢNG",
    stocks: [
      "DVP",
      "DXP",
      "GMD",
      "HAH",
      "PHP",
      "PVP",
      "PVT",
      "SGP",
      "SKG",
      "SWC",
      "TCL",
      "TCW",
      "VIP",
      "VOS",
      "VSC",
      "VTO",
      "GSP",
      "HHG",
      "TCO",
      "TMS",
      "VNA",
      "ILB",
      "PVP",
    ],
  },
  {
    name: "HOACHAT_PHANBON",
    displayName: "HÓA CHẤT - PHÂN BÓN",
    stocks: [
      "BFC",
      "CPC",
      "CSV",
      "DCM",
      "DGC",
      "DHB",
      "DOC",
      "DPM",
      "HIS",
      "LAS",
      "NFC",
      "PCE",
      "PMB",
      "PSE",
      "PSW",
      "QBS",
      "SFC",
      "SPC",
      "TSC",
      "VAF",
      "VFG",
      "VPS",
    ],
  },
  {
    name: "THUY_SAN",
    displayName: "THỦY SẢN",
    stocks: ["ACL", "ANV", "ASM", "CMX", "FMC", "IDI", "MPC", "VHC"],
  },
  {
    name: "THUC_PHAM",
    displayName: "THỰC PHẨM",
    stocks: [
      "AFX",
      "DBC",
      "DHC",
      "KDC",
      "LTG",
      "MHC",
      "MSN",
      "NAF",
      "PTB",
      "TNA",
      "VCS",
      "VLC",
      "VNM",
      "VOC",
      "APF",
      "BNA",
      "KDF",
      "MCM",
    ],
  },
  {
    name: "DIEN_NANGLUONG",
    displayName: "ĐIỆN - NĂNG LƯỢNG",
    stocks: [
      "KHP",
      "PPC",
      "PVG",
      "QTP",
      "VSH",
      "TTA",
      "GEG",
      "SJD",
      "NT2",
      "REE",
      "PC1",
      "HND",
      "GEX",
      "VNE",
      "BCG",
      "TV2",
    ],
  },
  {
    name: "HANGKHONG_DULICH",
    displayName: "HÀNG KHÔNG - DU LỊCH",
    stocks: ["ACV", "AST", "HVN", "SAS", "VJC", "VTD", "NCT", "DAH", "RIC"],
  },
  {
    name: "DUONG_GO",
    displayName: "ĐƯỜNG GỖ",
    stocks: ["GDT", "LSS", "QNS", "SBT", "TTF"],
  },
  {
    name: "NHUA_CAOSU",
    displayName: "NHỰA - CAO SU",
    stocks: [
      "AAA",
      "APC",
      "APP",
      "BRC",
      "BRR",
      "DAG",
      "DDV",
      "DPR",
      "DRG",
      "DRI",
      "DTT",
      "GVR",
      "HCD",
      "HII",
      "HNP",
      "HPH",
      "HRC",
      "IRC",
      "LNC",
      "LTG",
      "NHH",
      "NSG",
      "PCH",
      "PGN",
      "PHR",
      "PLC",
      "PLP",
      "RDP",
      "RTB",
      "SBV",
      "SIV",
      "TNC",
      "TPC",
      "TRC",
      "VNP",
    ],
  },
  {
    name: "DICH_VU",
    displayName: "DỊCH VỤ",
    stocks: ["HAX", "PAN", "TCT", "VNG", "VTP"],
  },
  {
    name: "DUOC",
    displayName: "DƯỢC",
    stocks: ["AMV", "DBD", "DCL", "DHG", "DMC", "DVN", "JVC", "TNH"],
  },
  {
    name: "CONG_NGHE",
    displayName: "CÔNG NGHỆ",
    stocks: ["CMG", "ELC", "FPT", "ICT", "SAM", "VEC"],
  },
  {
    name: "BAN_LE",
    displayName: "BÁN LẺ",
    stocks: [
      "MWG",
      "FRT",
      "PET",
      "HAX",
      "VEA",
      "PNJ",
      "TLG",
      "DGW",
      "MSN",
      "BBT",
      "CTF",
      "TMC",
      "MCH",
    ],
  },
];
